# Generated by Django 3.0.2 on 2020-02-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
