# Generated by Django 3.0.2 on 2020-02-27 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_public',
        ),
    ]
