# Generated by Django 3.0.2 on 2020-03-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_account_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='blog_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
