# Generated by Django 3.0.2 on 2020-02-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionary',
            old_name='code',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='dictionary',
            old_name='value',
            new_name='item_name',
        ),
        migrations.AddField(
            model_name='dictionary',
            name='item_name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
