# Generated by Django 3.0.2 on 2020-02-21 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='care/%Y/%m/%d')),
                ('desc', models.TextField(blank=True)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CareWeight',
            fields=[
                ('care_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pet.Care')),
                ('weight', models.IntegerField()),
            ],
            bases=('pet.care',),
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('bod', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='pet/%Y/%m/%d')),
                ('desc', models.TextField(blank=True)),
                ('is_keeping', models.BooleanField(default=True)),
                ('gender', models.ForeignKey(blank=True, limit_choices_to={'category': 'GT00000000'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gender', to='dict.Dictionary')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dict.AnimalDictionary')),
            ],
        ),
        migrations.AddField(
            model_name='care',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.Pet'),
        ),
        migrations.AddField(
            model_name='care',
            name='type',
            field=models.ForeignKey(limit_choices_to={'category': 'CT00000000'}, on_delete=django.db.models.deletion.CASCADE, related_name='care_type', to='dict.Dictionary'),
        ),
        migrations.CreateModel(
            name='CareFeeding',
            fields=[
                ('care_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pet.Care')),
                ('prey_weight', models.IntegerField(blank=True, null=True)),
                ('prey_quantity', models.IntegerField(default=1)),
                ('prey_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prey_size', to='dict.Dictionary')),
                ('prey_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prey_type', to='dict.Dictionary')),
            ],
            bases=('pet.care',),
        ),
    ]
