# Generated by Django 3.0.2 on 2020-02-08 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dict', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('bod', models.DateField()),
                ('image', models.ImageField(upload_to='pet/%Y/%m/%d')),
                ('desc', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('gender', models.ForeignKey(blank=True, limit_choices_to={'category': 'GT00000000'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gender', to='dict.Dictionary')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dict.AnimalDictionary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
