# Generated by Django 3.0.2 on 2020-02-08 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='have_end_date',
            field=models.DateField(default='9999-12-31'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='have_start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
