# Generated by Django 3.0.2 on 2020-02-22 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.ForeignKey(limit_choices_to={'category': 'GT00000000'}, on_delete=django.db.models.deletion.CASCADE, related_name='gender', to='dict.Dictionary'),
        ),
    ]
