# Generated by Django 3.0.2 on 2020-02-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_auto_20200208_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_keeping',
            field=models.BooleanField(default=True),
        ),
    ]
