# Generated by Django 3.0.2 on 2020-02-08 04:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pet', '0002_auto_20200208_1250'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Owner',
            new_name='Owned',
        ),
    ]
