# Generated by Django 3.0.2 on 2020-02-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_auto_20200222_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='bod',
            field=models.DateField(blank=True),
        ),
    ]
