# Generated by Django 3.0.2 on 2020-02-13 05:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
        ('pet', '0003_pet_is_keeping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, upload_to='care/%Y/%m/%d')),
                ('desc', models.TextField(blank=True)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pet.Pet')),
                ('type', models.ForeignKey(limit_choices_to={'category': 'CT00000000'}, on_delete=django.db.models.deletion.CASCADE, related_name='care_type', to='dict.Dictionary')),
            ],
        ),
    ]
