# Generated by Django 3.0.2 on 2020-03-04 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_auto_20200225_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
