# Generated by Django 3.0.2 on 2020-02-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_care'),
    ]

    operations = [
        migrations.AlterField(
            model_name='care',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='care/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pet/%Y/%m/%d'),
        ),
    ]
