# Generated by Django 3.0.2 on 2020-02-14 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_auto_20200214_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='is_public',
        ),
    ]
