# Generated by Django 3.0.2 on 2020-02-15 00:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0006_remove_pet_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='care',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.Pet'),
        ),
        migrations.CreateModel(
            name='CareWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('care', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.Care')),
            ],
        ),
    ]
