# Generated by Django 3.0.2 on 2020-02-15 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0007_auto_20200215_0947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CareWeight',
        ),
    ]
