# Generated by Django 3.0.2 on 2020-02-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0008_delete_careweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='care',
            name='care_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
