# Generated by Django 3.0.2 on 2020-02-18 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0009_care_care_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareWeight',
            fields=[
                ('care_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pet.Care')),
                ('weight', models.IntegerField()),
            ],
            bases=('pet.care',),
        ),
        migrations.RemoveField(
            model_name='care',
            name='care_value',
        ),
    ]
