# Generated by Django 3.0.2 on 2020-02-20 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
        ('pet', '0010_auto_20200218_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareFeeding',
            fields=[
                ('care_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pet.Care')),
                ('prey_weight', models.IntegerField(blank=True, null=True)),
                ('prey_quantity', models.IntegerField(default=1)),
                ('prey_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prey_size', to='dict.Dictionary')),
                ('prey_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prey_type', to='dict.Dictionary')),
            ],
            bases=('pet.care',),
        ),
    ]
