# Generated by Django 3.0.2 on 2020-02-21 07:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bbs.Post')),
                ('notice_from_date', models.DateField(default=django.utils.timezone.now)),
                ('notice_to_date', models.DateField(default=django.utils.timezone.now)),
            ],
            bases=('bbs.post',),
        ),
    ]
