# Generated by Django 3.0.2 on 2020-02-28 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
