# Generated by Django 3.0.2 on 2020-03-16 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_delete_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='board_status',
        ),
    ]
